name: touring
root: .
pre_window: source bashaliases.sh
windows:
  - editor:
      layout: 410c,179x146,0,0[179x127,0,0{127x127,0,0,0,51x127,128,0[51x87,128,0,1,51x39,128,88,3]},179x18,0,128,2]
      panes:
        - start # see bashaliases.sh
        - # cd client && npm run watch
        - watch -d --color -n 5 "git log --color --format='%C(auto,blue)%h%C(auto,reset) %C(auto,green)%an%C(auto,reset) %<(40,trunc)%s'"
        - watch -n 1 -d --color docker ps