version: '3'
services:
  server:
    build:
      context: web/
      dockerfile: Dockerfile.server
    networks:
      - server
      - client
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    image: httpd:2.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./client/build:/usr/local/apache2/htdocs/
    networks:
      - client
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - vdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: world
      POSTGRES_DB: pgdb
    restart: always
    networks:
      - server
volumes:
  vdata: {}
networks:
  server:
  client: